#!/bin/bash
echo "(1) touchdown, (2) hermes"
echo -n "BASE="
read base
echo "Sync start."
rm -rf "$PWD/System"
mkdir -p "$PWD/System"
clear
if [[ "$base" == "1" ]]; then
	cp -r "$PWD/base-touchdownos/" "$PWD/System/"
else
	cp -r "$PWD/base-hermes" "$PWD/System/"
fi
rm -rf "$PWD/System/.git"
rm -rf "$PWD/System/.gitattributes"
rm -rf "$PWD/System/.gitignore"
echo "Sync done."